name: Package Tests
on:
  pull_request:
    branches:
      - main
jobs:
  config-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install -e ./ukhsa_github[test]
      - run: pytest ./tests/test_ukhsa_github.py